POST localhost:8080/account/wallets/withdraw
Content-Type: application/json

{
  "accountId": "f4245629-83df-4ed8-90d9-7401045b5921",
  "walletId": "34534",
  "symbol": {
    "value": "ABC"
  },
  "amount": -50
}