micronaut:
    application:
        name: mn-stock-broker
    server:
        port: 8080

hello:
    controller:
        path: "/hello"
    service:
        greeting: "Hello from Service!"
    config:
        greeting:
            de: "Hallo"
            en: "Hello"

jackson:
    bean-introspection-module: true

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/mn-stock-broker
        username: ${PG_USERNAME:postgres}
        password: ${PG_PASSWORD:secret}
#        username: postgres
#        password: 'secret'
        driver-class-name: org.postgresql.Driver
#        schema-genenerate: CREATE_DROP
        dialect: POSTGRES
        schemas: mn
        default-schema: mn

jpa:
    default:
        properties:
            hibernate:
                bytecode:
                    provider: none
                hbm2ddl:
                    auto: validate
                show_sql: true
flyway:
    datasources:
        default:
            enabled: true
#            clean-schema: false
#            schemas: mn
#            default-schema: mn